# Generated by Django 5.2.7 on 2025-10-12 08:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('van', 'Van'), ('bus', 'Bus')], default='voiture', max_length=20)),
                ('confort', models.CharField(choices=[('standard', 'Standard'), ('confort', 'Confort'), ('vip', 'VIP')], default='standard', max_length=20)),
                ('tarif_km', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tarif_min', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('supplement', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('promo', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('taux', models.DecimalField(decimal_places=2, default=1.0, max_digits=5)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('telephone', models.CharField(max_length=30, unique=True)),
                ('email', models.EmailField(max_length=150, unique=True)),
                ('type_utilisateur', models.CharField(choices=[('passager', 'Passager'), ('chauffeur', 'Chauffeur'), ('admin', 'Administrateur')], default='passager', max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('suspendu', 'Suspendu'), ('supprimé', 'Supprimé')], default='actif', max_length=20)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point_depart', models.CharField(max_length=255)),
                ('point_arrivee', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duree_min', models.IntegerField()),
                ('prix', models.DecimalField(decimal_places=2, max_digits=10)),
                ('mode_paiement', models.CharField(choices=[('espèces', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], default='espèces', max_length=20)),
                ('statut_course', models.CharField(choices=[('en_attente', 'En attente'), ('en_cours', 'En cours'), ('terminée', 'Terminée'), ('annulée', 'Annulée')], default='en_attente', max_length=20)),
                ('note_passager', models.IntegerField(blank=True, null=True)),
                ('note_chauffeur', models.IntegerField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_fin', models.DateTimeField(blank=True, null=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses_chauffeur', to=settings.AUTH_USER_MODEL)),
                ('passager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses_passager', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.IntegerField()),
                ('commentaire', models.TextField(blank=True, null=True)),
                ('date_evaluation', models.DateTimeField(auto_now_add=True)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('cible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations_recues', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='menu.course')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('message', models.TextField()),
                ('statut', models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu')], default='non_lu', max_length=10)),
                ('date_envoi', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('moyen', models.CharField(choices=[('espèces', 'Espèces'), ('carte', 'Carte bancaire'), ('mobile_money', 'Mobile Money')], default='espèces', max_length=20)),
                ('statut', models.CharField(choices=[('réussi', 'Réussi'), ('échoué', 'Échoué'), ('en_attente', 'En attente')], default='en_attente', max_length=20)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='menu.course')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('derniere_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confort', models.CharField(choices=[('standard', 'Standard'), ('confort', 'Confort'), ('vip', 'VIP')], default='standard', max_length=20)),
                ('marque', models.CharField(max_length=100)),
                ('modele', models.CharField(max_length=100)),
                ('plaque', models.CharField(max_length=50)),
                ('couleur', models.CharField(max_length=50)),
                ('type_vehicule', models.CharField(choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('van', 'Van'), ('bus', 'Bus')], default='voiture', max_length=20)),
                ('capacite', models.IntegerField(default=4)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('réservé', 'Réservé')], default='actif', max_length=20)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
