# Generated by Django 5.2.7 on 2025-10-12 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_utilisateur_nom_utilisateur_post_nom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='utilisateur',
            name='nom',
        ),
        migrations.RemoveField(
            model_name='utilisateur',
            name='post_nom',
        ),
    ]
