# Generated by Django 5.2.7 on 2025-10-12 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_remove_utilisateur_nom_remove_utilisateur_post_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='taux',
            field=models.IntegerField(default=1),
        ),
    ]
