# Generated by Django 5.2.7 on 2025-10-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_alter_tarification_taux'),
    ]

    operations = [
        migrations.AddField(
            model_name='tarification',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
