# Generated by Django 5.2.7 on 2025-10-12 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0005_tarification_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tarification',
            name='prix',
        ),
    ]
