# Generated by Django 5.2.7 on 2025-10-12 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_remove_tarification_prix'),
    ]

    operations = [
        migrations.AddField(
            model_name='paiement',
            name='devise',
            field=models.CharField(default='CDF', max_length=10),
        ),
    ]
