# Generated by Django 5.2.7 on 2025-10-12 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0007_paiement_devise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='devise',
            field=models.CharField(choices=[('cdf', 'CDF'), ('usd', 'USD')], default='CDF', max_length=10),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='email',
            field=models.EmailField(max_length=150),
        ),
        migrations.AlterField(
            model_name='utilisateur',
            name='telephone',
            field=models.CharField(max_length=30),
        ),
    ]
