# Generated by Django 5.2.1 on 2025-10-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0008_alter_paiement_devise_alter_utilisateur_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='utilisateur',
            name='permis',
            field=models.ImageField(blank=True, null=True, upload_to='permis/'),
        ),
    ]
