# Generated by Django 5.2.7 on 2025-10-22 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0009_utilisateur_permis'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicule',
            name='image',
            field=models.ImageField(blank=True, help_text='Image ou photo du véhicule', null=True, upload_to='vehicules/'),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Latitude actuelle du véhicule', null=True),
        ),
        migrations.AddField(
            model_name='vehicule',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Longitude actuelle du véhicule', null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='plaque',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
