# Generated by Django 5.2.7 on 2025-10-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0010_vehicule_image_vehicule_latitude_vehicule_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='capacite',
            field=models.IntegerField(blank=True, default=4, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='confort',
            field=models.CharField(blank=True, choices=[('standard', 'Standard'), ('confort', 'Confort'), ('vip', 'VIP')], default='standard', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='couleur',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='marque',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='statut',
            field=models.CharField(blank=True, choices=[('actif', 'Actif'), ('en_maintenance', 'En maintenance'), ('hors_service', 'Hors service'), ('réservé', 'Réservé')], default='actif', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='vehicule',
            name='type_vehicule',
            field=models.CharField(blank=True, choices=[('moto', 'Moto'), ('voiture', 'Voiture'), ('van', 'Van'), ('bus', 'Bus')], default='voiture', max_length=20, null=True),
        ),
    ]
