# Generated by Django 5.2.7 on 2025-10-22 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0011_alter_vehicule_capacite_alter_vehicule_confort_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicule',
            name='plaque',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
