# Generated by Django 5.2.7 on 2025-10-22 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0012_alter_vehicule_plaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='image',
        ),
    ]
