# Generated by Django 5.2.7 on 2025-10-22 12:48

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0013_remove_vehicule_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tarification',
            options={'ordering': ['-date_creation']},
        ),
        migrations.RemoveField(
            model_name='course',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='course',
            name='duree_min',
        ),
        migrations.RemoveField(
            model_name='course',
            name='mode_paiement',
        ),
        migrations.RemoveField(
            model_name='course',
            name='note_chauffeur',
        ),
        migrations.RemoveField(
            model_name='course',
            name='note_passager',
        ),
        migrations.RemoveField(
            model_name='course',
            name='point_arrivee',
        ),
        migrations.RemoveField(
            model_name='course',
            name='point_depart',
        ),
        migrations.RemoveField(
            model_name='course',
            name='prix',
        ),
        migrations.RemoveField(
            model_name='course',
            name='statut_course',
        ),
        migrations.AddField(
            model_name='course',
            name='date_acceptation',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='depart_latitude',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='depart_longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='destination_latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='destination_longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='duree_estimee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='prix_estime',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='statut',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('acceptee', 'Acceptée'), ('en_cours', 'En cours'), ('terminee', 'Terminée'), ('annulee', 'Annulée')], default='en_attente', max_length=20),
        ),
        migrations.AddField(
            model_name='course',
            name='vehicule',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='menu.vehicule'),
        ),
    ]
