# Generated by Django 5.2.7 on 2025-10-22 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0014_alter_tarification_options_remove_course_distance_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='depart_latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='depart_longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='destination_latitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='destination_longitude',
            field=models.FloatField(blank=True, default=0.0, null=True),
        ),
    ]
