# Generated by Django 5.2.7 on 2025-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0015_alter_course_depart_latitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='tarif_km',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_min',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
