# Generated by Django 5.2.7 on 2025-10-22 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0016_alter_tarification_tarif_km_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='taux',
            field=models.IntegerField(default=2000),
        ),
    ]
