# Generated by Django 5.2.7 on 2025-10-22 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0017_alter_tarification_taux'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tarification',
            name='promo',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='supplement',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_km',
            field=models.FloatField(default=1),
        ),
        migrations.AlterField(
            model_name='tarification',
            name='tarif_min',
            field=models.FloatField(default=1),
        ),
    ]
