# Generated by Django 5.2.7 on 2025-10-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0018_alter_tarification_promo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prix_estime',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
