# Generated by Django 5.2.7 on 2025-10-25 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0019_alter_course_prix_estime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationPaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pourcentage_chauffeur', models.DecimalField(decimal_places=2, default=80.0, max_digits=5)),
                ('pourcentage_admin', models.DecimalField(decimal_places=2, default=20.0, max_digits=5)),
                ('date_modification', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration Paiement',
                'verbose_name_plural': 'Configuration Paiements',
            },
        ),
    ]
