# Generated by Django 5.2.7 on 2025-10-25 06:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0020_configurationpaiement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_amount_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('admin_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_amount_cdf', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('driver_amount_usd', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
