# Generated by Django 5.2.7 on 2025-10-25 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0021_wallet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='admin_amount_cdf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='admin_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='driver_amount_cdf',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='driver_amount_usd',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
