# Generated by Django 5.2.7 on 2025-10-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0022_alter_wallet_admin_amount_cdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='admin_amount_cdf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='admin_amount_usd',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='driver_amount_cdf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='driver_amount_usd',
            field=models.FloatField(default=0),
        ),
    ]
