# Generated by Django 5.2.7 on 2025-10-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0024_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='amount_cdf',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount_usd',
            field=models.FloatField(default=0),
        ),
    ]
